language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

before_script:
  - composer self-update
  - composer install

script:
  - mkdir -p build/cov build/logs
  - CALCULATOR=GMP    vendor/bin/phpunit --coverage-php build/cov/coverage-GMP.cov
  - CALCULATOR=BCMath vendor/bin/phpunit --coverage-php build/cov/coverage-BCMath.cov
  - CALCULATOR=Native vendor/bin/phpunit --coverage-php build/cov/coverage-Native.cov

after_script:
  - vendor/bin/phpcov merge --clover build/logs/clover.xml build/cov
  - vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: hhvm-nightly
