language: php

stages:
  - Smoke Testing
  - Test
  - Test (with coverage)

php:
  # 7.1 is included in the matrix below, with coverage
  - 7.2
  - 7.3
  # 7.4 is included in the matrix below, as base version for smoke testing
  - 8.0snapshot

env:
  - CALCULATOR=GMP
  - CALCULATOR=BCMath
  - CALCULATOR=Native

before_script:
  - |
    if [ $COVERAGE != "yes" ] && [ $TRAVIS_PHP_VERSION != "nightly" ]; then
      phpenv config-rm xdebug.ini
    fi
  - |
    if [ $TRAVIS_PHP_VERSION == "nightly" ]; then
      # not all dependencies advertise PHP 8 support yet
      composer config platform.php 7.4.0
    fi
  - composer install

script:
  - |
    if [ $COVERAGE == "yes" ]; then
      mkdir -p build/logs && vendor/bin/phpunit --coverage-clover build/logs/clover.xml
    else
      vendor/bin/phpunit
    fi

after_script:
  - |
    if [ $COVERAGE == "yes" ]; then
      vendor/bin/php-coveralls -v
    fi

jobs:
  include:
    - stage: Smoke Testing
      php: 7.4
      name: Psalm
      script: vendor/bin/psalm --show-info=false --find-unused-psalm-suppress --no-progress
    - stage: Smoke Testing
      php: 7.4
      env: CALCULATOR=GMP
    - stage: Smoke Testing
      php: 7.4
      env: CALCULATOR=BCMath
    - stage: Smoke Testing
      php: 7.4
      env: CALCULATOR=Native
    - stage: Test (with coverage)
      php: 7.1
      env: CALCULATOR=GMP COVERAGE=yes
    - stage: Test (with coverage)
      php: 7.1
      env: CALCULATOR=BCMath COVERAGE=yes
    - stage: Test (with coverage)
      php: 7.1
      env: CALCULATOR=Native COVERAGE=yes
