language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

before_script:
  - composer self-update
  - composer install
  - mkdir -p build/cov build/logs

script:
  - ./run-all-tests.sh build/cov

after_script:
  - vendor/bin/phpcov merge --clover build/logs/clover.xml build/cov
  - vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: hhvm-nightly
